#!/usr/bin/env node

const env = process.env.NODE_ENV || 'development';

switch (env) {
    case 'test':
        require('dotenv').load({
            path: '.env.testing'
        });
        break;
    default:
        require('dotenv').load();
        break;
}

const app = require('./app');

app.listen(process.env.PORT, () => {
    console.log(`App is running on port ${process.env.PORT}`);
});